const layerConfigs = {
  'est_rate': {'metric': 'Predicted LSL Rate (Average)',
    'description': '',
    'source': '',
    'paint': {'fill-color': ['interpolate',
      ['linear'],
      ['get', 'est_rate'],
      0.0,
      '#174e87',
      0.2,
      '#5ca3ea',
      0.3,
      '#f7d694',
      0.4,
      '#e8aa44',
      0.6,
      '#fb3939'],
    'fill-opacity': ['case',
    ['boolean', ['feature-state', 'hover'], false],
    0.85,
    0.5]}},
  'est_rate_low': {'metric': 'Predicted LSL Rate (Low)',
    'description': '',
    'source': 'https://www.epa.gov/ejscreen/ej-and-supplemental-indexes-ejscreen',
    'paint': {'fill-color': ['interpolate',
      ['linear'],
      ['get', 'est_rate_low'],
      0.0,
      '#174e87',
      0.1,
      '#5ca3ea',
      0.2,
      '#f7d694',
      0.3,
      '#e8aa44',
      0.4,
      '#fb3939'],
     'fill-opacity': ['case',
      ['boolean', ['feature-state', 'hover'], false],
      0.85,
      0.5]}},
  'est_rate_high': {'metric': 'Predicted LSL Rate (High)',
    'description': '',
    'source': 'https://www.epa.gov/ejscreen/ej-and-supplemental-indexes-ejscreen',
    'paint': {'fill-color': ['interpolate',
      ['linear'],
      ['get', 'est_rate_high'],
      0.0,
      '#174e87',
      0.2,
      '#5ca3ea',
      0.3,
      '#f7d694',
      0.4,
      '#e8aa44',
      0.6,
      '#fb3939'],
     'fill-opacity': ['case',
      ['boolean', ['feature-state', 'hover'], false],
      0.85,
      0.5]}},
  'eji': {'metric': 'EJ Index',
      'description': 'Average number of EJ Indexes exceeding 80 percentile in Census block groups within the water system service area.',
      'source': 'https://www.epa.gov/ejscreen/ej-and-supplemental-indexes-ejscreen',
      'paint': {'fill-color': ['interpolate',
        ['linear'],
        ['get', 'eji'],
        0.0,
        '#174e87',
        2,
        '#5ca3ea',
        4,
        '#f7d694',
        8,
        '#e8aa44',
        12,
        '#fb3939'],
       'fill-opacity': ['case',
        ['boolean', ['feature-state', 'hover'], false],
        0.85,
        0.5]}},
  'tier':{
    'metric':'Service area boundary type',
    'description':'',
    'source':'',
    'paint':{
      'fill-color':['case',
        ['==', ['get', 'tier'], 1], '#174e87',
        ['==', ['get', 'tier'], 2], '#f7d694',
        ['==', ['get', 'tier'], 3], '#fb3939',
        '#ffffff'
      ],
      'fill-opacity': ['case',
       ['boolean', ['feature-state', 'hover'], false],
       0.85, 0.5]
    },
  },
  'PRE1960PCT': {'metric': 'Pre-1960 Housing',
    'description': '',
    'source': 'https://www.epa.gov/ejscreen/ej-and-supplemental-indexes-ejscreen',
    'paint': {'fill-color': ['interpolate',
      ['linear'],
      ['get', 'PRE1960PCT'],
      0.0,
      '#174e87',
      0.2,
      '#5ca3ea',
      0.4,
      '#f7d694',
      0.6,
      '#e8aa44',
      0.8,
      '#fb3939'],
     'fill-opacity': ['case',
      ['boolean', ['feature-state', 'hover'], false],
      0.85,
      0.5]}},
  'service_connections_count': {'metric': 'Total service connections',
     'description': '',
     'source': 'https://www.epa.gov/ejscreen/ej-and-supplemental-indexes-ejscreen',
     'paint': {'fill-color': ['interpolate',
       ['linear'],
       ['get', 'service_connections_count'],
       10000,
       '#174e87',
       25000,
       '#5ca3ea',
       50000,
       '#f7d694',
       100000,
       '#e8aa44',
       250000,
       '#fb3939'],
      'fill-opacity': ['case',
       ['boolean', ['feature-state', 'hover'], false],
       0.85,
       0.5]}},
};
